config/routes.rb
Rails.application.routes.draw do

   root 'events#index'

     resources :events, only: [:index, :new, :create, :update, :edit, :destroy]

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
  validates :venue, presence: true
  validates :date, presence: true
  validates :time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @anything_to_show = Event.any?
  end

  def new
  	@event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path, notice: 'New event has been successfully added!'
    else
      flash.now.alert = 'Form incomplete - please ensure that you have filled out all fields.'
      render 'new'
    end
  end

  def update
   event = Event.find params[:id]
    if event.update_attributes(event_params)
      redirect_to events_path, :notice => 'Your event information has successfully been updated.'
    else
      redirect_to edit_event_path, :alert => 'There was an error updating your event information - please ensure that all fields have been completed.'
    end
  end

  def edit
    @event = Event.find params[:id]
  end

  def destroy
    Event.destroy params[:id]
    redirect_to events_path, :notice => "Event has been deleted."
  end

  private

  def event_params
    params.require(:event).permit(
        :name,
        :venue,
        :date,
        :time
        )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_table.html.erb
<div class="row">
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th width="200">Event name</th>
          <th width="150">Venue</th>
          <th width="150">Date</th>
          <th width="150">Time</th>
          <th width="150"></th>
          <th width="150"></th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.venue %></td>
            <td><%= event.date.strftime("%d/%m/%Y") %></td>
            <td><%= event.time.strftime("%H:%M %P") %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Delete', event, :method => 'delete' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/edit.html.erb
 <div class="twelve columns">
   <div class="row">
    <div class="large-4 columns" %>
      <br>
      <h1><img class="logo" src="/img/logo.png">Edit Event</h1>
      </br>
    </div>
  </div>
</div>
<%= form_for @event do |f| %>
<div class="row text-center">
  <div class="large-12 columns" %>
    <div class="row text-center">
      <div class="large-4 columns">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row text-center">
      <div class="large-4 columns">
        <%= f.label :venue %>
        <%= f.text_field :venue %>
      </div>
    </div>
    <div class="row text-center">
      <div class="large-2 columns">
        <%= f.label :date %>
        <%= f.date_select :date %>
      </div>
    <div class="large-2 columns">
      <%= f.label :time %>
      <%= f.time_select :time %>
    </div>
    <div class="row ">
      <div class="large-12 columns" %>
        <%= f.submit 'Update', class: 'button success button expand round' %>
      </div>
    </div>
    </div>
  </div>
</div>
<% end %>

app/views/events/index.html.erb
<div class="twelve columns text-center">
  <h1><img class="logo" src="/img/logo.png">Spring Forward Events Planner!</h1>
  <h5>Keep track of all the awesome events you are attending as part of <a href="http://www.wespringforward.com" target="_blank">Spring Forward Festival</a></h5>
  <br>
  <%= link_to 'Add new event', new_event_path, class: 'button success button round' %>
  <% if @anything_to_show %>
    <%=  render 'table' %>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="twelve columns">
  <div class="row">
    <div class="large-4 columns" %>
     <br>
     <h1><img class="logo" src="/img/logo.png">Add Event</h1>
     </br>
    </div>
  </div>
</div>
<%= form_for @event, html: {role: "form"} do |f| %>
  <div class="row text-center">
    <div class="large-12 columns" %>
      <div class="row text-center">
        <div class="large-4 columns">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>
    <div class="row text-center">
      <div class="large-4 columns">
        <%= f.label :venue %>
        <%= f.text_field :venue %>
      </div>
    </div>
    <div class="row text-center">
      <div class="large-2 columns">
        <%= f.label :date %>
        <%= f.date_select :date %>
       </div>
    <div class="large-2 columns">
      <%= f.label :time %>
      <%= f.time_select :time %>
    </div>
   <div class="row ">
      <div class="large-12 columns" %>
        <%= f.submit 'Add new event', class: 'button success expand' %>
      </div>
    </div>
    </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SF Events planner" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Spring Forward Events Planner', new_event_path %></h1>
      </li>
    </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="active"><%= link_to 'Return home', root_path %></li>
    </ul>
</nav>
    <% if flash[:notice] %>
      <div data-alert class="alert-box success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div data-alert class="alert-box alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>